"""GENERATED FILE -- DO NOT EDIT BY HAND.

Auto-generated by rag_kernel.guardgen (generator v1.0.0) from the
formally-verified TLA+ model. Regenerate with:

    python -m rag_kernel.guardgen --tla RAGKernel.tla --out <this file>

Provenance
----------
  source         : RAGKernel.tla
  source sha256  : 268149294421ae6c2f41c116b9f9298fe53678b998ee0dd652b9092548533ecc
  generator      : rag_kernel.guardgen v1.0.0

This module is the runtime projection of the model's transition table and
action enabling-conditions. Editing it by hand defeats the formal-verification
guarantee: the model (checked by TLC) is the single source of truth. To change
a guard, change formal/RAGKernel.tla, re-run TLC, then regenerate.

@rag-kernel-manifest
{
  "module": "rag_kernel.generated_guards",
  "capability": "generated_guards",
  "description": "TLA+-derived transition table and action enabling-guards",
  "exports": ["GENERATED_TRANSITIONS", "KernelContext", "GuardResult",
              "ACTION_GUARDS", "legal_transition", "SOURCE_SHA256",
              "GUARDS_SELF_SHA256", "verify_self"],
  "use_when": "Enforcing structurally-verified state transitions (FV-PHASE4)",
  "never_bypass": true,
  "generated": true
}
"""

from __future__ import annotations

from dataclasses import dataclass

# SHA-256 of the source .tla this module was generated from. Compared at
# import/verify time to detect model/code drift (needs the .tla to recompute).
SOURCE_SHA256 = "268149294421ae6c2f41c116b9f9298fe53678b998ee0dd652b9092548533ecc"
# SHA-256 of THIS module's own guard tables (STATES / TERMINAL_STATES /
# GENERATED_TRANSITIONS / ACTION_GUARDS), baked at generation time. Lets a
# DEPLOYED package that ships no formal/RAGKernel.tla self-verify its guard
# integrity from baked provenance -- see verify_self() at the foot of this file.
GUARDS_SELF_SHA256 = "9a88156777efb5e4f3fb582ad114231131f6441471d3d4d3e798a9dbcea10d7e"
GENERATOR_VERSION = "1.0.0"

GuardResult = tuple[bool, str]



STATES = frozenset({'BOOTING', 'READY', 'INGESTING', 'WORKING', 'CHECKPOINTING', 'CLOSING', 'RECOVERY'})
TERMINAL_STATES = frozenset({'CLOSING'})
CRASH_ELIGIBLE_STATES = STATES - TERMINAL_STATES


GENERATED_TRANSITIONS: dict[str, frozenset[str]] = {
    'BOOTING': frozenset({'READY', 'RECOVERY'}),
    'READY': frozenset({'CHECKPOINTING', 'CLOSING', 'INGESTING', 'WORKING'}),
    'INGESTING': frozenset({'CHECKPOINTING', 'READY', 'RECOVERY'}),
    'WORKING': frozenset({'CHECKPOINTING', 'READY', 'RECOVERY'}),
    'CHECKPOINTING': frozenset({'CLOSING', 'READY', 'RECOVERY'}),
    'CLOSING': frozenset(),
    'RECOVERY': frozenset({'BOOTING', 'READY'}),
}


@dataclass(frozen=True)
class KernelContext:
    """Snapshot of the model's state variables, consumed by the guards.

    Mirrors the VARIABLES block of RAGKernel.tla:
      state, proposalStatus, proposalTarget, wal (via wal_len), crashed,
      plus the MaxWALSeq bound.
    """

    state: str
    proposal_status: str = "NONE"
    proposal_target: str = "BOOTING"
    wal_len: int = 0
    crashed: bool = False
    max_wal_seq: int = 8


def legal_transition(from_state: str, to_state: str) -> bool:
    """True iff from_state -> to_state is in the generated transition table."""
    return to_state in GENERATED_TRANSITIONS.get(from_state, frozenset())


def guard_clear_rejection(ctx: KernelContext) -> GuardResult:
    """Enabling guard for TLA+ action ClearRejection.

    Preconditions (from the model):
      - proposalStatus = REJECTED
    """
    if not (ctx.proposal_status == 'REJECTED'):
        return (False, 'ClearRejection precondition failed: proposalStatus = REJECTED')
    return (True, '')


def guard_commit_proposal(ctx: KernelContext) -> GuardResult:
    """Enabling guard for TLA+ action CommitProposal.

    Preconditions (from the model):
      - ~crashed
      - proposalStatus = STAGED
      - IsLegalTransition(state, proposalTarget)
      - WALSeq < MaxWALSeq
    """
    if not (not ctx.crashed):
        return (False, 'CommitProposal precondition failed: ~crashed')
    if not (ctx.proposal_status == 'STAGED'):
        return (False, 'CommitProposal precondition failed: proposalStatus = STAGED')
    if not (ctx.proposal_target in GENERATED_TRANSITIONS.get(ctx.state, frozenset())):
        return (False, 'CommitProposal precondition failed: IsLegalTransition(state, proposalTarget)')
    if not (ctx.wal_len < ctx.max_wal_seq):
        return (False, 'CommitProposal precondition failed: WALSeq < MaxWALSeq')
    return (True, '')


def guard_crash(ctx: KernelContext) -> GuardResult:
    """Enabling guard for TLA+ action Crash.

    Preconditions (from the model):
      - state \\in CrashEligibleStates
      - ~crashed
    """
    if not (ctx.state in CRASH_ELIGIBLE_STATES):
        return (False, 'Crash precondition failed: state \\in CrashEligibleStates')
    if not (not ctx.crashed):
        return (False, 'Crash precondition failed: ~crashed')
    return (True, '')


def guard_direct_transition(ctx: KernelContext, target: str) -> GuardResult:
    """Enabling guard for TLA+ action DirectTransition.

    Preconditions (from the model):
      - ~crashed
      - proposalStatus = NONE
      - IsLegalTransition(state, target)
      - WALSeq < MaxWALSeq
    """
    if not (not ctx.crashed):
        return (False, 'DirectTransition precondition failed: ~crashed')
    if not (ctx.proposal_status == 'NONE'):
        return (False, 'DirectTransition precondition failed: proposalStatus = NONE')
    if not (target in GENERATED_TRANSITIONS.get(ctx.state, frozenset())):
        return (False, 'DirectTransition precondition failed: IsLegalTransition(state, target)')
    if not (ctx.wal_len < ctx.max_wal_seq):
        return (False, 'DirectTransition precondition failed: WALSeq < MaxWALSeq')
    return (True, '')


def guard_recovery_complete(ctx: KernelContext, target: str) -> GuardResult:
    """Enabling guard for TLA+ action RecoveryComplete.

    Preconditions (from the model):
      - crashed
      - state = RECOVERY
      - target \\in AllowedTargets(RECOVERY)
      - WALSeq < MaxWALSeq
    """
    if not (ctx.crashed):
        return (False, 'RecoveryComplete precondition failed: crashed')
    if not (ctx.state == 'RECOVERY'):
        return (False, 'RecoveryComplete precondition failed: state = RECOVERY')
    if not (target in GENERATED_TRANSITIONS.get('RECOVERY', frozenset())):
        return (False, 'RecoveryComplete precondition failed: target \\in AllowedTargets(RECOVERY)')
    if not (ctx.wal_len < ctx.max_wal_seq):
        return (False, 'RecoveryComplete precondition failed: WALSeq < MaxWALSeq')
    return (True, '')


def guard_reject_proposal(ctx: KernelContext) -> GuardResult:
    """Enabling guard for TLA+ action RejectProposal.

    Preconditions (from the model):
      - ~crashed
      - proposalStatus = STAGED
    """
    if not (not ctx.crashed):
        return (False, 'RejectProposal precondition failed: ~crashed')
    if not (ctx.proposal_status == 'STAGED'):
        return (False, 'RejectProposal precondition failed: proposalStatus = STAGED')
    return (True, '')


def guard_stage_proposal(ctx: KernelContext, target: str) -> GuardResult:
    """Enabling guard for TLA+ action StageProposal.

    Preconditions (from the model):
      - ~crashed
      - proposalStatus = NONE
      - state \\in {READY, WORKING}
      - IsLegalTransition(state, target)
      - WALSeq < MaxWALSeq
    """
    if not (not ctx.crashed):
        return (False, 'StageProposal precondition failed: ~crashed')
    if not (ctx.proposal_status == 'NONE'):
        return (False, 'StageProposal precondition failed: proposalStatus = NONE')
    if not (ctx.state in ('READY', 'WORKING')):
        return (False, 'StageProposal precondition failed: state \\in {READY, WORKING}')
    if not (target in GENERATED_TRANSITIONS.get(ctx.state, frozenset())):
        return (False, 'StageProposal precondition failed: IsLegalTransition(state, target)')
    if not (ctx.wal_len < ctx.max_wal_seq):
        return (False, 'StageProposal precondition failed: WALSeq < MaxWALSeq')
    return (True, '')


def guard_wal_compaction(ctx: KernelContext) -> GuardResult:
    """Enabling guard for TLA+ action WALCompaction.

    Preconditions (from the model):
      - state \\notin TerminalStates
      - Len(wal) >= 2
      - proposalStatus = NONE
    """
    if not (ctx.state not in TERMINAL_STATES):
        return (False, 'WALCompaction precondition failed: state \\notin TerminalStates')
    if not (ctx.wal_len >= 2):
        return (False, 'WALCompaction precondition failed: Len(wal) >= 2')
    if not (ctx.proposal_status == 'NONE'):
        return (False, 'WALCompaction precondition failed: proposalStatus = NONE')
    return (True, '')


# Action name -> (guard callable, takes_target).
ACTION_GUARDS: dict[str, tuple] = {
    'ClearRejection': (guard_clear_rejection, False),
    'CommitProposal': (guard_commit_proposal, False),
    'Crash': (guard_crash, False),
    'DirectTransition': (guard_direct_transition, True),
    'RecoveryComplete': (guard_recovery_complete, True),
    'RejectProposal': (guard_reject_proposal, False),
    'StageProposal': (guard_stage_proposal, True),
    'WALCompaction': (guard_wal_compaction, False),
}


# ---------------------------------------------------------------------------
# Baked self-verification (deployed packages ship no .tla to recompute against)
# ---------------------------------------------------------------------------

def _guards_payload() -> str:
    """Canonical, order-stable serialization of this module's guard tables.

    Must match ``guardgen.canonical_guard_payload`` byte-for-byte so the baked
    GUARDS_SELF_SHA256 verifies at runtime without the formal source.
    """
    _lines = []
    _lines.append("STATES=" + ",".join(sorted(STATES)))
    _lines.append("TERMINAL=" + ",".join(sorted(TERMINAL_STATES)))
    for _k in sorted(GENERATED_TRANSITIONS):
        _lines.append("T:" + _k + "=" + ",".join(sorted(GENERATED_TRANSITIONS[_k])))
    for _name, _meta in sorted(ACTION_GUARDS.items()):
        _lines.append("A:" + _name + "=" + ("1" if _meta[1] else "0"))
    return "\n".join(_lines)


def verify_self() -> bool:
    """True iff the in-memory guard tables match the baked GUARDS_SELF_SHA256.

    Lets a DEPLOYED package prove its own guard integrity from baked provenance:
    a post-generation hand-edit to STATES / TERMINAL_STATES / GENERATED_TRANSITIONS
    / ACTION_GUARDS changes the payload and fails this check. Returns False (never
    raises) on any mismatch or missing bake.
    """
    import hashlib as _hashlib
    if not GUARDS_SELF_SHA256:
        return False
    _got = _hashlib.sha256(_guards_payload().encode("utf-8")).hexdigest()
    return _got == GUARDS_SELF_SHA256

